# Tp Reconaissance des chiffres

In [1]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)

KeyboardInterrupt: 

In [2]:
# Le dataset principal qui contient toutes les images
print (mnist.data.shape)

# Le vecteur d'annotations associé au dataset (nombre entre 0 et 9)
print (mnist.target.shape)

(70000, 784)
(70000,)


In [3]:
import numpy as np

sample = np.random.randint(70000, size=1000)
data = mnist.data.iloc[sample]
target = mnist.target.iloc[sample]

In [4]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(data, target, train_size=0.8)

In [5]:
xtrain=xtrain.values
xtest=xtest.values
ytrain=ytrain.values
ytest=ytest.values


In [6]:
from MyKNNLIB import *

In [7]:
matrice=ConfusionMatrix(xtest,ytest,(xtrain,ytrain,d1,11))
print(matrice)

[[19.  0.  0.  0.  0.  2.  1.  0.  0.  0.]
 [ 1. 17.  0.  0.  1.  7.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  4.  0.  0.  0.  0.]
 [ 0.  0.  0. 15.  1.  1.  7.  0.  0.  0.]
 [ 1.  0.  0.  0. 15.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 25.  0.  0.  0.  0.]
 [ 0.  0.  2.  2.  0.  0. 16.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0. 14.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  3.  0. 11.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0. 15.]]
